version: '3.5'

services:
    database:
        image: mariadb:10.2
        environment:
            MYSQL_ROOT_PASSWORD: 'admin'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'admin'
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - ./app/:/app
            - ./docker/app/entrypoint.sh:/usr/local/bin/entrypoint.sh
        ports:
            - 80:80
        environment:
            APP_NAME: website
            DATABASE_URL: mysql://root:admin@database/app
            SECRET_KEY: secret
            DEBUG: 'True'
        depends_on:
            - database